Metrics/CyclomaticComplexity:
  Enabled: false

# Avoid excessive block nesting
Metrics/BlockNesting:
  Enabled: false

# Numbers with underscores, please.
Style/NumericLiterals:
  Enabled: true

# Allow more complex if statements ( if { if { if {} } })
Metrics/AbcSize:
  Max: 30

# Allow slightly longer modules
Metrics/ModuleLength:
  CountComments: false
  Max: 150

# Allow slightly longer classes
Metrics/ClassLength:
  CountComments: false
  Max: 150

# Allow sightly longer lines
Metrics/LineLength:
  Max: 150

# Allow slightly longer block length
Metrics/BlockLength:
  Max: 150

# Allow slightly longer methods
Metrics/MethodLength:
  Max: 150

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space
AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'examples/**/*'
    - 'features/**/*'
